version: '3.9'

services:
    test-localstack:
        container_name: test-localstack
        image: localstack/localstack
        ports:
            # - "127.0.0.1:53:53"
            # - "127.0.0.1:53:53/udp"
            # - "127.0.0.1:443:443"
            # - "127.0.0.1:4510-4530:4510-4530"
            # - "127.0.0.1:4566:4566"
            # - "127.0.0.1:4571:4571"
            - 443:443
            - 4510-4530:4510-4530
            - 4566:4566
            - 4571:4571
            # - 4600:4600 # EC2 Starter - VM manager
            # - 8080:8080 # TODO: web ui not working!
        environment:
            - LOCALSTACK_API_KEY=${LOCALSTACK_LICENSE}
            - USE_LIGHT_IMAGE=1
            - IMAGE_NAME=localstack/localstack
            - MAIN_CONTAINER_NAME=test-localstack
            - SERVICES=cloudformation,cloudfront,apigateway,apigatewayv2,iam,secretsmanager,lambda,s3,sqs,sts,ec2,kafka,elb,elbv2
            - DEFAULT_REGION=us-east-1
            # - DATA_DIR=/tmp/localstack/data
            # - HOST_TMP_FOLDER=${TMPDIR}
            # - LAMBDA_REMOTE_DOCKER=false
            - AWS_ACCESS_KEY_ID=test
            - AWS_SECRET_ACCESS_KEY=test
            - EAGER_SERVICE_LOADING=1
            - S3_SKIP_SIGNATURE_VALIDATION=1
            - LAMBDA_CONTAINER_REGISTRY=mlupin/docker-lambda
            # - LAMBDA_DOCKER_DNS=8.8.8.8
            # - DNS_ADDRESS=0
            # - DNS_ADDRESS=8.8.8.8
            - DEBUG=1
            # - LS_LOG=trace # uncomment for detailed logs
        volumes:
            # - ${TMPDIR:-/tmp/localstack}:/tmp/localstack
            - /var/run/docker.sock:/var/run/docker.sock
        network_mode: bridge
